### ISSUE TITLE
config.js not present (building docker image)

### ISSUE THREAD

**Issue by nvdk** [AKSW/context#29]
As mentioned in #25 config.js is not present and should be created.

Currently running docker build . results in the following error:

```
Step 13 : RUN gulp build
 ---> Running in 87fe7d7dd1be

module.js:340                                                                                                                                                         
    throw err;                                                                                                                                                        
          ^                                                                                                                                                           
Error: Cannot find module '../../config'                                                                                                                              
    at Function.Module._resolveFilename (module.js:338:15)                                                                                                            
    at Function.Module._load (module.js:280:25)                                                                                                                       
    at Module.require (module.js:364:17)                                                                                                                              
    at require (module.js:380:17)                                                                                                                                     
    at Object.<anonymous> (/opt/app/gulp/tasks/vendor.js:2:14)                                                                                                        
    at Module._compile (module.js:456:26)                                                                                                                             
    at Object.Module._extensions..js (module.js:474:10)                                                                                                               
    at Module.load (module.js:356:32)                                                                                                                                 
    at Function.Module._load (module.js:312:12)                                                                                                                       
    at Module.require (module.js:364:17)                                                                                                                              
2014/09/08 16:10:04 The command [/bin/sh -c gulp build] returned a non-zero code: 8
```

This was resolved by copying config.example.js to config.js

**Comment by yamalight** [comment]
Thanks for reporting! Added new step to docker readme part.
